### ISSUE TITLE
Autofix not working

### ISSUE THREAD

**Issue by henryruhs** [krema/angular-eslint-stylelint-builder#122]
This feature has properly never been implemented but it would be good to support autofix for eslint and stylelint using `ng lint --fix`. Thanks

Edit: Once the fix option is set inside `angular.json` the whole linting does not work at all!

**Comment by krema** [comment]
Fixed! Please recheck with version 1.2.2

**Comment by henryruhs** [comment]
I can confirm, works for eslint and stylelint - either via cli and option in angular.json ... thanks
