### ISSUE TITLE
Provide tsConfig in options

### ISSUE THREAD

**Issue by henryruhs** [krema/angular-eslint-stylelint-builder#90]
It would be nice to have this option, because sometimes you need to provide different configs for linting. In my projects I usualy have to add cypress types to the main tsconfig.json so the lint command is passing. Not ideal...

```
"options": {
	"tsConfig": "tsconfig.lint.json"
}
```

**Comment by krema** [comment]
This can be done by eslintrc.json 

```
"parserOptions": {
  "project": "./tsconfig.json"
}
```
and the config parameter **eslintConfig**

**Comment by henryruhs** [comment]
okay, that is a valid solution...
