### ISSUE TITLE
Not working on Windows10

### ISSUE THREAD

**Issue by AlexMelov** [krema/angular-eslint-stylelint-builder#94]
I have issue running on windows 10, it throws me an error:
An unhandled exception occurred: No files matching the pattern  project\src\**\**\*.scss" were found.

**Comment by krema** [comment]
is your path correct? 

`project/src/**/*.scss`

**Comment by krema** [comment]
@AlexMelov Could you fix the pattern? I'm closing this for now. Please feel free to reopen it if you need help.

**Comment by henryruhs** [comment]
Please reopen - this is not solved... you need to escape the paths for stylelint
